//ACA VAN TODOS LOS TIPOS DE ACCIONES

//ejemplo
//cars
export const GETALLCARS='GETALLCARS'
export const CARFILTERS='CARFILTERS'
export const CARDETAIL='CARDETAIL'
export const GETCARBYNAME='GETCARBYNAME'
export const CLEARDETAIL='CLEARDETAIL'

//categories
export const GETALLCATEGORIES='GETALLCATEGORIES'
export const CREATECATEGORY='CREATECATEGORY'
export const UPDATECATEGORY='UPDATECATEGORY'
export const DELETECATEGORY='DELETECATEGORY'


//brands
export const GETALLBRANDS='GETALLBRANDS'
export const CREATEBRAND='CREATEBRAND'
export const UPDATEBRAND='UPDATEBRAND'
export const DELETEBRAND='DELETEBRAND'


//users
export const GETALLUSERS='GETALLUSERS'
export const CREATEUSER='CREATEUSER'
export const UPDATEUSER='UPDATEUSER'
export const DISABLEUSER='DISABLEUSER'
export const ENABLEUSER='ENABLEUSER'

