//ACA VAN TODOS LOS TIPOS DE ACCIONES

//ejemplo
export const GETALLCARS='GETALLCARS'
export const CARDETAIL='CARDETAIL'
export const GETCARBYNAME='GETCARBYNAME'
export const CLEARDETAIL='CLEARDETAIL'
export const CARFILTERS='CARFILTERS'
export const GETALLBRANDS='GETALLBRANDS'
export const GETALLCATEGORIES='GETALLCATEGORIES'